@startuml
actor Comprador
boundary "Interfície Comandes"
control "Gestor Comandes"
entity Comanda
entity DadesComprador
control "Gestor Maps"
control "Gestor Pagament"
boundary "Interfície Maps"
control "Interfície Pagament"
actor "Google Maps" <<extern>>
actor "PayPal / Banc" <<extern>>

' --- 1, 2 i 3. INICI I CÀLCUL DE PREU AMB GOOGLE MAPS ---
Comprador -> "Interfície Comandes" : ContinuarPagament()
activate "Interfície Comandes"

"Interfície Comandes" -> "Gestor Comandes" : CalcularPreuFinal()
activate "Gestor Comandes"

"Gestor Comandes" -> Comanda : obtenirDetalls()
activate Comanda
Comanda --> "Gestor Comandes" : dades (productes, adreces)
deactivate Comanda

' Càlcul de distància delegat a l'actor extern
"Gestor Comandes" -> "Gestor Maps" : demanarDistancia(origen, desti)
activate "Gestor Maps"
"Gestor Maps" -> "Interfície Maps" : calcularDistancia(origen, desti)
activate "Interfície Maps"
"Google Maps" -> "Interfície Maps" : Distància()
"Interfície Maps" --> "Gestor Maps" : return()
deactivate "Interfície Maps"
"Gestor Maps" --> "Gestor Comandes" : return ()
deactivate "Gestor Maps"

' --- S2. PUNTS DE SUBSCRIPCIÓ ---
opt S2 (Punts de subscripció)
    "Gestor Comandes" -> DadesComprador : consultarPunts()
    activate DadesComprador
    DadesComprador --> "Gestor Comandes" : puntsAcumulats
    deactivate DadesComprador
end

"Gestor Comandes" -> Comanda : calcularPreuTotal(distancia)
activate Comanda
Comanda --> "Gestor Comandes" : preuFinal
deactivate Comanda

"Gestor Comandes" --> "Interfície Comandes" : MostrarPreuFinal(preuFinal)
deactivate "Gestor Comandes"

' --- 4 i 5. PROCÉS DE PAGAMENT ---
Comprador -> "Interfície Comandes" : PagarComanda()

"Interfície Comandes" -> "Gestor Comandes" : ProcessarPagament()
activate "Gestor Comandes"

' Càlcul de distància delegat a l'actor extern
"Gestor Comandes" -> "Gestor Pagament" : GestionarPagament()
activate "Gestor Pagament"
"Gestor Pagament" -> "Interfície Pagament" : DemanarPagament()
activate "Interfície Pagament"
"PayPal / Banc" -> "Interfície Pagament" : DadesPagament()
"Interfície Pagament" --> "Gestor Pagament" : return()
deactivate "Interfície Pagament"
"Gestor Pagament" --> "Gestor Comandes" : return ()
deactivate "Gestor Maps"

' --- A1. ERROR EN EL PAGAMENT ---
alt A1 (Error en el pagament)
    "Gestor Pagament" --> "Gestor Comandes" : TransaccioDenegada()
    "Gestor Comandes" --> "Interfície Comandes" : ErrorPagament()
else Pagament Correcte
    "Gestor Pagament" --> "Gestor Comandes" : TransaccioExitosa()
    deactivate "Gestor Pagament"

    ' --- 6. CONFIRMACIÓ I FACTURA ---
    "Gestor Comandes" -> Comanda : actulitzarEstat(PAGADA)
    activate Comanda
    Comanda --> "Gestor Comandes" : return
    deactivate Comanda

    "Gestor Comandes" --> "Interfície Comandes" : ConfirmacioIPresentarFactura()
    deactivate "Gestor Comandes"
end

deactivate "Interfície Comandes"

@enduml
